### ISSUE TITLE
Admin Access

### ISSUE THREAD

**Issue by swarnap** [aimhigherweb/tech-outsiders#20]
I just signed up for an account (per the instructions on https://techoutsiders.com.au/about/) and I seem to have been granted admin rights.  I could've easily deleted all existing speaker profiles.  Is that the expected experience?  Or is there a different way for me to request my profile to be added without being given the ability to make drastic changes?

**Comment by amykapernick** [comment]
Hey @swarnap we're aware of this, unfortunately we can't restrict who can edit what (but have requested that functionality). We're trusting that people will do the right thing, and all changes are made to the dev branch so check what changes have been made before making them live.

**Comment by amykapernick** [comment]
@swarnap we've just pushed through a change for this, you can now add new locations. I've added one for San Francisco so you should be good to finish your profile!
